name: check_script
on:
  pull_request:
    branches:
      - main
jobs:
  ci_check:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          python --version
          python3 --version
          which python
          which python3
          which pip
          which pip3
      - name: build1
        run: |
          cd data
          ls -la esci-data
      - name: build2
        run: |
          cd data
          pip3 install -r requirement.txt
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        run: |
          cd data
          python3 create_shopping_data.py
