name: check_script
on:
  pull_request:
    branches:
      - main
jobs:
  ci_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #   with:
      #     submodules: recursive
      #     lfs: true
      # - name: build
      #   run: |
      #     cd data
      #     pip3 install -r requirement.txt
      # - name: create_data
      #   run: |
      #     mkdir -p jmeter/benchmarks
      #     mkdir -p jmeter/benchmarks/benchmark-solr
      #     cd data
      #     python3 create_shopping_data.py
      #     python3 create_shopping_query.py > ../jmeter/benchmarks/queries.txt
      - name: build_solr
        run: |
          DOCKER_BUILDKIT=1 docker-compose up -d --build
      - name: feed_amazon_shopping_data
        run: |
          docker-compose exec solr1 /opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost zoo:2181 -cmd upconfig -confdir /opt/solr/configsets/amazonshopping -confname amazonshopping
          curl 'localhost:8983/solr/admin/collections?action=CREATE&name=amazonshopping&numShards=2&replicationFactor=2&maxShardsPerNode=2&collection.configName=amazonshopping'
          for docs in $(ls ./data/amazonshopping/*.json); do curl -X POST -H 'Content-Type: application/json' --data-binary @$docs 'http://localhost:8983/solr/amazonshopping/update?commit=true'; done
      - name: benchmark
        run: |
          docker-compose exec -u root jmeter benchmark-solr -c amazonshopping -z zoo:2181 -q /var/jmeter/benchmarks/queries.txt -t 233 -d 60 --extract-expression '$.response.numFound' --extract-expression '$.responseHeader.QTime' --clean
