name: check_script
on:
  pull_request:
    branches:
      - main
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: |
          cd data
          ls -la esci-data
          # pip3 install -r requirement.txt
          # python3 create_shopping_data.py
