name: check_script
on:
  pull_request:
    branches:
      - main
jobs:
  ci_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # lfs: true

      - name: Build and start containers
        run: |
          cd solrcloud-development-box
          docker-compose up -d

      - name: Wait for containers to start
        run: sleep 10

      - name: Test Solr containers
        run: |
          curl http://localhost:8983/solr/admin/cores?action=STATUS # Solr1の通信確認
          curl http://localhost:8984/solr/admin/cores?action=STATUS # Solr2の通信確認
      # - name: build
      #   run: |
      #     cd data
      #     pip3 install -r requirement.txt
      # - name: create_data
      #   run: |
      #     mkdir -p jmeter/benchmarks
      #     mkdir -p jmeter/benchmarks/benchmark-solr
      #     cd data
      #     python3 create_shopping_data.py
      #     python3 create_shopping_query.py > ../jmeter/benchmarks/queries.txt
